# Generated by Django 4.0.6 on 2022-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ceo', 'Ceo'), ('branch', 'Branch'), ('director', 'Director'), ('administrator', 'Administrator'), ('limited', 'Limited'), ('teacher', 'Teacher'), ('student', 'Student'), ('marketer', 'Marketer'), ('cashier', 'Cashier')], default='student', max_length=25),
        ),
    ]
